import { mat } from './matrix';
declare function addInPlace(leftMatrix: mat, rightMatrix: mat): mat;
declare function add(leftMat: mat, rightMat: mat): mat;
declare function minusInPlace(leftMatrix: mat, rightMatrix: mat): mat;
declare function minus(leftMat: mat, rightMat: mat): mat;
declare function mul(leftMat: mat, rightMat: mat): mat;
declare function mulInPlace(leftMat: mat, rightMat: mat): mat;
declare function dotMulInPlace(leftMat: mat, rightMat: mat): mat;
declare function dotMul(leftMat: mat, rightMat: mat): mat;
declare function mul_gpu(leftMat: mat, rightMat: mat): mat;
declare function x_mul_xT(inMat: mat): mat;
declare function xT_mul_x(inMat: mat): mat;
export { add, addInPlace, minus, minusInPlace, mul, mulInPlace, mul_gpu, x_mul_xT, xT_mul_x, dotMul, dotMulInPlace };
